### ISSUE TITLE
Develop Branch does'nt compile on pi3+

### ISSUE THREAD

**Issue by pmgiHu** [rfkd/aircontrol#10]
Hello.
I would like to use the replay feature but the development code does'nt make/compile on a raspi 3b+. Should it? 
The master branch does make/compile.
Tell me if I should paste the errors.

The master branch seems not to have the COOL replay feature.
I tried hard two nights not to bother you but now I would be glad for support. 
Kind Regards, Peter

p.s. I want to control Warema ewfs jalousies but the protocol seems to be overcomplicated.

**Comment by rfkd** [comment]
Hi Peter,

the develop branch should always build. Are WiringPi and libconfig++-dev installed on your Raspberry Pi as described in the README? Please post the complete build log (output of the `make` command) so I can see what's wrong.

Once it's working it would be nice to get some feedback from you how the air replay feature works in a real environment as I'm controlling my Warema EWFS shutters as regular targets. Getting the Manchester code from an air scan is also not complicated once you've learned how to read the air scan file. If air replay is not working stable I can also support you in decoding your shutter commands.

By the way, don't worry about asking questions.

Regards,
Ralf

**Comment by pmgiHu** [comment]
Dear Ralf,
thank you for your fast and friendly response. I really appreciate your support.

I followed the installation instructions:

wiringpi is installed:

pi@rpi3p:~ $ gpio -v
gpio version: 2.50
Copyright (c) 2012-2018 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Raspberry Pi Details:
  Type: Pi 3B+, Revision: 03, Memory: 1024MB, Maker: Sony 
  * Device tree is enabled.
  *--> Raspberry Pi 3 Model B Plus Rev 1.3
  * This Raspberry Pi supports user-level GPIO access.

libconfig++ also installed:

pi@rpi3p:~ $ sudo apt-get install libconfig++-dev
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
libconfig++-dev ist schon die neueste Version (1.5-0.4).                       <----------Translation
Das folgende Paket wurde automatisch installiert und wird nicht mehr benötigt:
  rpi.gpio-common
Verwenden Sie »sudo apt autoremove«, um es zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

Translation: ... libconfig++-dev is already the newest version (1.5-0.4)
And the master branch works. 


The build output is:

pi@rpi3p:~ $ cd aircontrol
pi@rpi3p:~/aircontrol $ make
g++ -c -std=c++14 -Wall -Wno-unused-result -Iinclude -MMD -MP -MF build/Task.d -o build/Task.o source/Task.cpp
In file included from include/Task.h:24,
                 from source/Task.cpp:22:
include/Configuration.h: In member function ‘bool Configuration::getValue(std::__cxx11::string, std::__cxx11::string, T&) const’:
include/Configuration.h:56:44: error: no match for ‘operator[]’ (operand types are ‘libconfig::Setting’ and ‘const string’ {aka ‘const std::__cxx11::basic_string<char>’})
             return configuration_.getRoot()[section].lookupValue(name, value);
                                            ^
In file included from include/Configuration.h:26,
                 from include/Task.h:24,
                 from source/Task.cpp:22:
/usr/include/libconfig.h++:223:13: note: candidate: ‘libconfig::Setting& libconfig::Setting::operator[](const char*) const’
   Setting & operator[](const char *name) const;
             ^~~~~~~~
/usr/include/libconfig.h++:223:13: note:   no known conversion for argument 1 from ‘const string’ {aka ‘const std::__cxx11::basic_string<char>’} to ‘const char*’
/usr/include/libconfig.h++:224:13: note: candidate: ‘libconfig::Setting& libconfig::Setting::operator[](int) const’
   Setting & operator[](int index) const;
             ^~~~~~~~
/usr/include/libconfig.h++:224:13: note:   no known conversion for argument 1 from ‘const string’ {aka ‘const std::__cxx11::basic_string<char>’} to ‘int’
make: *** [Makefile:43: build/Task.o] Fehler 1

hm Looks like a libconfig issue, right?

Another question: Does the EWFS protocol need a connection between the 433-remote-control an the receiver? I am scanning the rc signal in my cellar workshop. There is no connection to the receiver there. 

Thanks in advance,
Peter

p.s. The two Warema jalousies are the weak link in my smart home chain. I need to get it at least lifted up when strong wind comes up.

**Comment by rfkd** [comment]
Hi Peter,

seems like libconfig++ v1.5 (your version) is not compatible with v1.4 (which is the lastest version on my Pi). Can you try installing v1.4? I'll check asap whether I can support both versions.

Warema EWFS (as opposed to Warema WMS) is unidirectional, so you don't need a connection to the receiver for signal analysis.

**Comment by pmgiHu** [comment]
Hai Ralf,
of course. Searching how to downgrade ...

**Comment by pmgiHu** [comment]
Hi Ralf,
I downgraded to 1.4.9. 
>>Die folgenden Pakete sind zurückgehalten worden: // apt-get suggest to upgrade ...
>>   libconfig++-dev (1.4.9-2 => 1.5-0.4)

The build was more successful , but still erroneous:
make
g++ -c -std=c++14 -Wall -Wno-unused-result -Iinclude -MMD -MP -MF build/Task.d -o build/Task.o source/Task.cpp
g++ -c -std=c++14 -Wall -Wno-unused-result -Iinclude -MMD -MP -MF build/Configuration.d -o build/Configuration.o source/Configuration.cpp
g++ -c -std=c++14 -Wall -Wno-unused-result -Iinclude -MMD -MP -MF build/ReplayParameters.d -o build/ReplayParameters.o source/ReplayParameters.cpp
g++ -c -std=c++14 -Wall -Wno-unused-result -Iinclude -MMD -MP -MF build/Replay.d -o build/Replay.o source/Replay.cpp
g++ -c -std=c++14 -Wall -Wno-unused-result -Iinclude -MMD -MP -MF build/TargetParameters.d -o build/TargetParameters.o source/TargetParameters.cpp
g++ -c -std=c++14 -Wall -Wno-unused-result -Iinclude -MMD -MP -MF build/ScanParameters.d -o build/ScanParameters.o source/ScanParameters.cpp
g++ -c -std=c++14 -Wall -Wno-unused-result -Iinclude -MMD -MP -MF build/aircontrol.d -o build/aircontrol.o source/aircontrol.cpp
g++ -c -std=c++14 -Wall -Wno-unused-result -Iinclude -MMD -MP -MF build/Scan.d -o build/Scan.o source/Scan.cpp
g++ -c -std=c++14 -Wall -Wno-unused-result -Iinclude -MMD -MP -MF build/Target.d -o build/Target.o source/Target.cpp
g++ -c -std=c++14 -Wall -Wno-unused-result -Iinclude -MMD -MP -MF build/InstanceLock.d -o build/InstanceLock.o source/InstanceLock.cpp
g++ -lconfig++ -lwiringPi build/Task.o build/Configuration.o build/ReplayParameters.o build/Replay.o build/TargetParameters.o build/ScanParameters.o build/aircontrol.o build/Scan.o build/Target.o build/InstanceLock.o -o bin/aircontrol
/usr/bin/ld: build/TargetParameters.o: in function `libconfig::Setting::lookupValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const':
TargetParameters.cpp:(.text._ZNK9libconfig7Setting11lookupValueERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS6_[_ZNK9libconfig7Setting11lookupValueERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS6_]+0x30): undefined reference to `libconfig::Setting::lookupValue(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
collect2: error: ld returned 1 exit status
make: *** [Makefile:39: bin/aircontrol] Fehler 1

sudo'ing the make does'nt help.

What exact version number does work on your raspi?

**Comment by rfkd** [comment]
On my Raspberry Pi 3B I'm running Raspbian 8 (stretch) with:
```
ii  libconfig++-dev:armhf             1.4.9-2                          armhf
ii  libconfig++9:armhf                1.4.9-2                          armhf
```
Please post the output of `dpkg -l | grep libconfig`.

Yesterday in the evening I setup a QEMU emulation of Raspbian 10 (buster) - according to your libconfig++ version it's the OS version you're using as well? Haven't started with the integration of libconfig++ 1.5-0.4 though, maybe I find some time at the weekend.

**Comment by rfkd** [comment]
Can you switch back to libconfig++ 1.5-0.4 and try building  the branch `feature-build_with_libconfig++_1.5` and report the result?

**Comment by pmgiHu** [comment]
OS-Version is buster:
pi@rpi3p:~ $ uname -a
Linux rpi3p 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l GNU/Linux
pi@rpi3p:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by pmgiHu** [comment]
libconfig Version switched back to 1.5-0.4:

pi@rpi3p:~ $ dpkg -l | grep libconfig
ii  libconfig++-dev:armhf                 1.5-0.4                               armhf        parsing/manipulation of structured config files (C++ development)
rc  libconfig++9:armhf                    1.4.9-2                               armhf        parsing/manipulation of structured configuration files (C++ binding)
ii  libconfig++9v5:armhf                  1.5-0.4                               armhf        parsing/manipulation of structured configuration files (C++ binding)
ii  libconfig-dev:armhf                   1.5-0.4                               armhf        parsing/manipulation of structured config files (development)
ii  libconfig-doc                         1.5-0.4                               all          parsing/manipulation of structured config files (Documentation)
ii  libconfig9:armhf                      1.5-0.4                               armhf        parsing/manipulation of structured configuration files

Now I start checking out the new dev branch an try it...

**Comment by pmgiHu** [comment]
The build worked! Thanks for your support.
Now I start testing the current features and hope I will get the jalousies up and down.
