### ISSUE TITLE
Signature mismatch when replaying

### ISSUE THREAD

**Issue by pmgiHu** [rfkd/aircontrol#12]
Dear Ralf,
I tried to replay but got an errormessage while replaying:

_pi@rpi3p:~ $ aircontrol -c devbranchaircontrol.conf -r up.asd 
Error: Given file is not an air scan dump (signature mismatch)
pi@rpi3p:~ $ aircontrol -c devbranchaircontrol.conf -r nosig.asd 
Error: Given file is not an air scan dump (signature mismatch)_

nosig.asd represends a one second scan without sending from the warema remote. up.asd is a three second file with a press of UP-button.

The devbranchaircontrol.conf is a renamed copy of the aircontrol.conf from the develoment branch, as the original version does not contain a replay section.

Here are the zipped .asd and the .conf File:
[signatureErr.zip](https://github.com/rfkd/aircontrol/files/3464834/signatureErr.zip)

**Comment by rfkd** [comment]
Hi Peter,

you have to use the `-d` parameter to dump the scan results into a replay file. The normal console output of the scan (without `-d`) is for manual (human) analysis.

To record a dump file run the following command. Keep the UP button pressed while recording.
`# aircontrol -c devbranchaircontrol.conf -d up.asd -s 1000`

To replay the recorded file run:
`# aircontrol -c devbranchaircontrol.conf -r up.asd`

**Comment by pmgiHu** [comment]
Hi Ralf,
this way scan and replay does run without errors.
Thanks, Peter

**Comment by rfkd** [comment]
Can you control your shutters with replay? Please report back any issues.

**Comment by pmgiHu** [comment]
Replay doesn't lift the shutter while scanning the signal 4m from the receiver does.

My analysis:
1. Sender not working?
2. replay to low signal strength, distance too far // but 4m?
3. up2.asd not ok // the second shutter according to my remote

Thus I recorded a (remote-)successfull up (4m from the receiver) // aircontrol -d up2.asd -c devbranchaircontrol.conf -s 3000 >> 
[upPlayedAndReceived.zip](https://github.com/rfkd/aircontrol/files/3468399/upPlayedAndReceived.zip)
shutters do go up
Started a 9000ms scan task in the background // aircontrol -d up2_received.asd -c devbranchaircontrol.conf -s 9000 &
replayed the scan // aircontrol -c devbranchaircontrol.conf -r up2.asd 

up2.asd and up2.received.asd are in the zip attached.

Be sure I will doublecheck the HW-wiring but can you interpret whether replaying did result in sendig correct signals?

**Comment by rfkd** [comment]
> Replay doesn't lift the shutter while scanning the signal 4m from the receiver does.

What is that supposed to mean? Are you able to control at least one shutter in any direction or none at all?

First you need to ensure that your transmitter is working. According to the scan results you posted in the opening post the receiver side seems fine (apart from some artefacts). I decoded three signals out of *up.asd* (taken from *signatureErr.zip*) for you manually, see an example here: https://pastebin.com/64WuaCD5

Two times the signal resulted in the following air comand:
```
airCommand =
        "S01110100111111"
        "S011010101"
        "S000001000"
        "S";
```

Once like this (try this one as well if the upper one does not work):
```
airCommand =
        "S01110100111111
        "S011010101
        "S000001011
        "S";
```

Configure it as a normal Warema target (like `warema_example`). By the way, my other parameters are:

```
dataLength = 1780;
syncLength = 5000;
sendCommand = 20;
sendDelay = 25000;
```

Have a look at [Manchester Code - Issue #1](https://github.com/rfkd/aircontrol/issues/1) for more discussions about signal decoding. Once you get used to reading the scan graph decoding will be pretty fast.

Which kind of transmitter hardware are you using and how is the antenna setup?

By the way, don't record for such a long time, instead try to time recording and button pressing better - one to three seconds should be enough. A nine seconds dump/replay makes no sense.

**Comment by pmgiHu** [comment]
Meaning of "Replay ...": When I was recording the sample the remote lifted the shutter, while no replay did.
The transmitted is working. It switches a 433-plug-socked, that was 5m away from the transmitter.

I tried  both airCommands and wasn't successful. Thank you anyway for decoding.
I will have a look at the Manchester Code to learn decoding on my own as soon as possible.

The transmitter is a "Aukru 433 MHz Funk- Sende und Empfänger Modul Superregeneration Wireless Transmitter-Modul". Currently no extra antenna. The antennas are not yet delivered. 
Is it possible that the transmitted signal is too weak without an antenna? But the socket was 6m away and switched whether the shutters are only 4m away.

**Comment by rfkd** [comment]
Are there any walls inbetween? Can you try to reduce the distance even more and increase the `sendCommand` value (this simulates a longer button press on the remote)? Otherwise wait for the antenna or build one on your own. 

At home I'm using two transmitters with two self-built antennas at 45° angle. That way I can step and drive all EWFS shutters very stable.

**Comment by pmgiHu** [comment]
Dear Ralf,
I bought a new sender with antenna, because delivery of the antenna was postponed.

It works!

warema_sample:
{
    // Air command to be transmitted (values defined by airCode)
    // twice like this
    aircode = 0;
    airCommand =
        "S01110100111111"
        "S011010101"
        "S000001000"
        "S";

};

Asap I will try the replay feature and start to understand the Manchester encoding.

Regards, Peter
