### ISSUE TITLE
Migration to Arduino/ESP8266

### ISSUE THREAD

**Issue by philipptrenz** [rfkd/aircontrol#19]
Hey there, 

I'm running aircontrol commands from an Raspberry Pi and would like to migrate the sending of my decoded commands to an ESP8266 because auf power consumption and maintenance reasons. Has anyone done this before? Any help is highly appreciated!

Thanks!

**Comment by philipptrenz** [comment]
P.S. My command are manchester ones

**Comment by rfkd** [comment]
Hey,

you would have to port parts of `aircontrol` to the ESP. It is currently implemented as a Linux application with configuration files and GPIO access via `wiringPi`. Adapting the GPIO access shouldn't be too much effort, for the configuration you'd have to find another solution (e.g. make it editable via web interface or similar). The logic could be reused.

Sounds interesting, let me know if you start something.

**Comment by philipptrenz** [comment]
Hi @rfkd,

thanks for your reply and your assessment! I'll keep you posted if I ever get around to it. I will close the issue in the meantime.

**Comment by glitchracer** [comment]
Any progress here? I'm also interested to move to ESP or even to a USB 433 transceiver, unfortunately I don't know where to start with that. 

Please help.
